window.onload = () => {
    getVersionNumber();
    let headStyles = `
    <link rel="stylesheet" href="CSS/HeadersAndDefaults.css?v=${versionNumber}">
    <link rel="stylesheet" href="CSS/Character.css?v=${versionNumber}">
    <link rel="stylesheet" href="CSS/Audioplayer.css?v=${versionNumber}">
    <link rel="stylesheet" href="CSS/CollapsibleGroup.css?v=${versionNumber}">
    <link rel="stylesheet" href="CSS/HrStyles.css?v=${versionNumber}">
    <link rel="stylesheet" href="CSS/Nav.css?v=${versionNumber}">
    `;
    document.querySelector('head').innerHTML += headStyles;
    let player = document.querySelector('#player');
    player.pause();
    CreateNavbar();
    document.querySelector('#BasicInfo').innerHTML= `
    <p class='question'>Birth Name</p>
    <p class="answer">Abagael Zondervan (Fun fact, Dutch don't have middle names. If they had 3 names, it would be 2 first names and 1 last name)</p>
    <p class='question'>Current Name</p>
    <p class="answer">Adam Zondervan</p>
    <div class="brLarge"></div>
    <p class='question'>Birth First Name</p>
    <p class="answer">Abagael</p>
    <p class='question'>Meaning</p>
    <p class="answer">Father of joy</p>
    <div class="brLarge"></div>
    <p class='question'>Current First Name</p>
    <p class="answer">Adam</p>
    <p class='question'>Meaning</p>
    <p class="answer">Red Earth</p>
    <p class='question'>Significance</p>
    <p class="answer">He did not care about the meaning when he chose this name, he just wanted something somewhat close to his birth name</p>
    <div class="brLarge"></div>
    <p class='question'>Last Name</p>
    <p class="answer">Zondervan</p>
    <p class='question'>Meaning</p>
    <p class="answer">Without a surname</p>
    <div class="brLarge"></div>
    <p class='question'>Nicknames</p>
    <p class="answer">Addy</p>
    <div class="brLarge"></div>
    <p class='question'>Biological Gender</p>
    <p class="answer">Female</p>
    <p class='question'>Preferred Gender</p>
    <p class="answer">Male</p>
    <p class='question'>Pronouns</p>
    <p class="answer">He/him</p>
    <div class="brLarge"></div>
    <p class='question'>Sexual Orientation</p>
    <p class="answer">Pansexual</p>
    <p class='question'>Romantic Orientation</p>
    <p class="answer">Panromantic</p>
    <div class="brLarge"></div>
    <p class='question'>Age</p>
    <p class="answer">22 - 23</p>
    <p class='question'>Birthday</p>
    <p class="answer">May 24th</p>
    <p class='question'>Zodiac Sign</p>
    <p class="answer">Gemini</p>
    <div class="brLarge"></div>
    <p class='question'>Occupation</p>
    <p class="answer">Guitarist</p>
    <div class="brLarge"></div>
    <p class='question'>Where they live</p>
    <p class="answer">Prismoria</p>
    <div class="brLarge"></div>
    <p class='question'>Languages</p>
    <p class="answer">Dutch</p>
    <p class="answer">English</p>
    <p class="answer">French</p>
    <p class="answer">Spanish</p>`;
    document.querySelector('#Health').innerHTML = `
    <p class='question'>Physical Illnesses</p>
    <p class="answer">Heart disease</p>
    <p class='question'>Mental Illnesses</p>
    <p class="answer">None</p>
    <div class="brLarge"></div>
    <p class='question'>Triggers</p>
    <p class="answer">None that is known of</p>
    <div class="brLarge"></div>
    <p class='question'>Mutation / Power</p>
    <p class="answer">Wind Manipulation</p>
    <p class='question'>How long have they had it</p>
    <p class="answer">About 7 years</p>
    <p class='question'>How do they use it</p>
    <p class="answer">Shutting doors, picking things up, annoying people</p>`;
    document.querySelector('#Appearance').innerHTML = `
    <p class='question'>Height</p>
    <p class="answer">5'7"</p>
    <p class="answer">170.18 cm</p>
    <p class='question'>Weight</p>
    <p class="answer">123 lbs.</p>
    <p class="answer">55.79 kg</p>
    <div class="brLarge"></div>
    <p class='question'>Hair color</p>
    <p class="answer">Light brown</p>
    <div class="brLarge"></div>
    <p class='question'>Eye color(s)</p>
    <p class="answer">Hazel</p>
    <div class="brLarge"></div>
    <p class='question'>Piercings</p>
    <p class="answer">None</p>
    <p class='question'>Scars</p>
    <p class="answer">None</p>
    <p class='question'>Tattoos</p>
    <p class="answer">None</p>
    <p class='question'>Birthmark</p>
    <p class="answer">Some discoloration on his left forearm</p>
    <p class='question'>Freckles</p>
    <p class="answer">Yes</p>
    <div class="brLarge"></div>
    <p class='question'>Accent / Voice</p>
    <p class="answer">He has a Dutch accent. It's not that thick, but when he gets worried or scared, it does become more prominent in his voice. His laugh is also very infectious</p>`;
    document.querySelector('#RpInfo').innerHTML=`
    <p class='question'>Availability</p>
    <p class="answer">Open</p>
    <div class="brLarge"></div>
    <p class='question'>Genres</p>
    <p class="answer">Fantasy</p>
    <p class="answer">Angst</p>
    <p class="answer">Sci-Fi</p>
    <p class="answer">Romance</p>`;
    document.querySelector('#Relations').innerHTML=`
    <p class='question'>Mother</p>
    <p class="answer">Mila Zondervan</p>
    <p class='question'>Status</p>
    <p class="answer">Dying</p>
    <div class="brLarge"></div>
    <p class='question'>Father</p>
    <p class="answer">Stijn Zondervan</p>
    <p class='question'>Status</p>
    <p class="answer">Dead</p>
    <div class="brLarge"></div>
    <p class='question'>Sister</p>
    <p class="answer">Roseline Zondervan</p>
    <p class='question'>Status</p>
    <p class="answer">Alive</p>
    <div class="brLarge"></div>
    <p class='question'>Sister</p>
    <p class="answer">Fleur Zondervan</p>
    <p class='question'>Status</p>
    <p class="answer">Alive</p>`;
    document.querySelector('#Perception').innerHTML = `
    <p class='question'>How they feel about themselves</p>
    <p class='answer'>Adam is confident with himself. He doesn't dislike himself for the most part.</p>
    <div class='brLarge'></div>
    <p class='question'>How they would describe themselves</p>
    <p class='answer'>An ambivert who likes to play guitar and have fun with friends.</p>
    <div class='brLarge'></div>
    <p class='question'>What they think is their best trait</p>
    <p class='answer'>His sense of humor</p>
    <div class='brLarge'></div>
    <p class='question'>What they think is their worst trait</p>
    <p class='answer'>His inability to get over his fears</p>
    <div class='brLarge'></div>
    <p class='question'>How they think other perceive them</p>
    <p class='answer'>The funny but reliable friend</p>
    <div class='brLarge'></div>
    <p class='question'>What they would like to change about themselves</p>
    <p class='answer'>His gender assigned at birth</p>`;
    document.querySelector('#Personality').innerHTML = `
    <p class='question'>Closest Stereotype</p>
    <p class="answer">Goofball</p>
    <p class='question'>Overall Description</p>
    <p class="answer">Adam is a pretty chill guy when you first meet him. He's not exactly outgoing, nor is he timid. He's just an average, nice guy. Once he gets to know someone and becomes friends with them, he opens up a bit more and starts playing around with them. He can be really funny and he also likes to tease people, but he is respectful of their boundaries. If someone tells him that they genuinely dislike when he jokes around about xyz, he'll never mention it around them again, and he expects they will do the same for him. Also, he does like to swear. It's not excessive, but he does swear.</p>
    <div class="brLarge"></div>
    <p class='question'>Likes</p>
    <p class="answer">Laughter. In general. Felt like it was cheating to say "Making people laugh/smile", "The sound of laughter", "Being able to make someone cry from laughing so much" and "People who make him laugh as well" in separate bullets, so now it's just one</p>
    <p class="answer">Hot chocolate. He will drink it as much as other people will drink coffee</p>
    <p class="answer">Pulling pranks and just playing around with friends</p>
    <p class="answer">Soft, fluffy things</p>
    <p class="answer">Sweaters</p>
    <div class="brLarge"></div>
    <p class='question'>Dislikes</p>
    <p class="answer">Being called adorable or pretty. He can take cute, but he grew up in a family of only girls and used to be a girl himself. Those words are just too girly to him</p>
    <p class="answer">Snow and the cold. He gets cold easily</p>
    <p class="answer">Super serious, all work people</p>
    <p class="answer">Violations of personal space / constant physical affection</p>
    <div class="brLarge"></div>
    <p class='question'>Positive Traits</p>
    <p class="answer">He's playful, funny, and charming</p>
    <p class="answer">Open about most of his issues. He's not secretive and won't hold a grudge</p>
    <p class="answer">Protective and loyal towards his friends</p>
    <div class="brLarge"></div>
    <p class='question'>Negative Traits</p>
    <p class="answer">He is not open about his health issues</p>
    <p class="answer">He doesn't take things seriously sometimes</p>
    <p class="answer">He lets his fears dictate his future</p>
    <div class="brLarge"></div>
    <p class='question'>Fears</p>
    <p class="answer">That he has Huntington's just like his mother. He's too scared to get tested. And he's scared of passing that on if he ever has kids</p>
    <p class="answer">Spiders or really any creepy crawly bugs</p>
    <p class="answer">Heights</p>
    <div class="brLarge"></div>
    <p class='question'>Hobbies</p>
    <p class="answer">Playing the guitar</p>
    <p class="answer">Writing in his diary</p>
    <div class="brLarge"></div>
    <p class='question'>Love Language(s)</p>
    <p class="answer">Quality Time: This love language is all about giving your undivided attention to that one special person, without the distraction of television, phone screens, or any other outside interference. They have a strong desire to actively spend time with their significant other, having meaningful conversations or sharing recreational activities.</p>`;
};