window.onload = () => {
    getVersionNumber();
    let headerText = document.querySelector('head').innerHTML;
    let headSubstring;
    let headStyles = `
    <link rel="stylesheet" href="CSS/HeadersAndDefaults.css?v=${versionNumber}">
    <link rel="stylesheet" href="CSS/Character.css?v=${versionNumber}">
    <link rel="stylesheet" href="CSS/Audioplayer.css?v=${versionNumber}">
    <link rel="stylesheet" href="CSS/CollapsibleGroup.css?v=${versionNumber}">
    <link rel="stylesheet" href="CSS/HrStyles.css?v=${versionNumber}">
    <link rel="stylesheet" href="CSS/Nav.css?v=${versionNumber}">
    `;
    headSubstring = headerText.substring(headerText.indexOf("<link rel=\"stylesheet\" href=\"CSS/"), 
    headerText.indexOf("href=\"CSS/Nav.css\">") + 20);
    document.querySelector('head').innerHTML = document.querySelector('head').innerHTML.replace(headSubstring, headStyles);
    let player = document.querySelector('#player');
    player.pause();
    CreateNavbar();
    document.querySelector('#BasicInfo').innerHTML= `
    <p class="question">Birth Name</p>
    <p class="answer">Elliot Servius Evans</p>
    <p class="question">Current Name</p>
    <p class="answer">Elliot Servius Evans</p>
    <div class='brLarge'></div>
    <p class="question">First Name</p>
    <p class="answer">Elliot</p>
    <p class="question">Meaning</p>
    <p class="answer">"God on high," "The Lord is my God"</p>
    <div class='brLarge'></div>
    <p class="question">Middle Name</p>
    <p class="answer">Servius</p>
    <p class="question">Meaning</p>
    <p class="answer">"To preserve"</p>
    <div class='brLarge'></div>
    <p class="question">Last Name</p>
    <p class="answer">Evans</p>
    <p class="question">Meaning</p>
    <p class="answer">"The Lord is gracious"</p>
    <div class='brLarge'></div>
    <p class="question">Nicknames</p>
    <p class="answer">Elli</p>
    <div class='brLarge'></div>
    <p class="question">Biological Gender</p>
    <p class="answer">Male</p>
    <p class="question">Preferred Gender</p>
    <p class="answer">Male</p>
    <p class="question">Pronouns</p>
    <p class="answer">He / his / him</p>
    <div class='brLarge'></div>
    <p class="question">Sexual Orientation</p>
    <p class="answer">Asexual</p>
    <p class="question">Romantic Orientation</p>
    <p class="answer">Panromantic</p>
    <div class='brLarge'></div>
    <p class="question">Age</p>
    <p class="answer">42</p>
    <p class="question">Birthday</p>
    <p class="answer">August 23rd</p>
    <p class="question">Zodiac Sign</p>
    <p class="answer">Virgo</p>
    <div class='brLarge'></div>
    <p class="question">Occupation</p>
    <p class="answer">CEO of a laboratory organization</p>
    <div class='brLarge'></div>
    <p class="question">Where they live</p>
    <p class="answer">Prismoria</p>
    <div class='brLarge'></div>
    <p class="question">Languages</p>
    <p class="answer">English</p>`;
    document.querySelector('#Health').innerHTML = `
    <p class="question">Physical Illnesses</p>
    <p class="answer">Mutation</p>
    <div class='brLarge'></div>
    <p class="question">Mental Illnesses</p>
    <p class="answer">Dissociative Identity Disorder</p>
    <div class='brLarge'></div>
    <p class="question">Triggers</p>
    <p class="answer">Guns</p>
    <p class="answer">Cameras</p>
    <p class="answer">A lot of things, really</p>
    <div class='brLarge'></div>
    <p class="question">Mutation / Power</p>
    <p class="answer">Mutation</p>
    <p class="question">How long have they had it</p>
    <p class="answer">About 12 years</p>
    <p class="question">Description</p>
    <p class="answer">He has an internal mutation that causes him sudden and sharp pain. It's very subtle to tell, but this pain is because the mutation is literally pulling in one of his limbs very slightly and consuming it. That makes the mutation grow. This also happens during sleep. However, this means that he is getting smaller. His arms and legs are getting shorter. Not proportionally even, the mutation is pulling in the limb to consume, so the distance between his shoulder and elbow is getting shorter and not the distance between his elbow and wrist. But it's so subtle and small, that it's very hard to tell, especially not if you see him everyday. Maybe if you saw him after a long time, when the mutation has had time to consume a lot</p>`;
    document.querySelector('#Appearance').innerHTML = `
    <p class="question">Height</p>
    <p class="answer">5'9.5" currently, he used to be 6'3.5"</p>
    <p class="answer">176.53 cm currently, he used to be 191.77 cm</p>
    <p class="question">Weight</p>
    <p class="answer">127 lbs.</p>
    <p class="answer">57.61 kg</p>
    <div class='brLarge'></div>
    <p class="question">Hair color</p>
    <p class="answer">Minecraft dirt block brown</p>
    <p class="question">Hair style</p>
    <p class="answer">Straight, parted in the middle, medium length</p>
    <div class='brLarge'></div>
    <p class="question">Eye color(s)</p>
    <p class="answer">Murky green</p>
    <div class='brLarge'></div>
    <p class="question">Piercings</p>
    <p class="answer">None</p>
    <p class="question">Scars</p>
    <p class="answer">A few from when he's tried to have a doctor remove the mutation. It inevitably failed, but he still has the scars</p>
    <p class="question">Tattoos</p>
    <p class="answer">None</p>
    <p class="question">Birthmark</p>
    <p class="answer">None</p>
    <p class="question">Freckles</p>
    <p class="answer">No</p>`;
    document.querySelector('#RpInfo').innerHTML=`
    <p class="question">Availability</p>
    <p class="answer">Open</p>
    <div class='brLarge'></div>
    <p class="question">Genres</p>
    <p class="answer">Fantasy</p>
    <p class="answer">Angst</p>
    <p class="answer">Sci-Fi</p>
<p class="answer">Romance</p>`;
    document.querySelector('#Relations').innerHTML=`
    <p class="question">Mother</p>
    <p class="answer">Linda Evans</p>
    <p class="question">Status</p>
    <p class="answer">Dead</p>
    <div class='brLarge'></div>
    <p class="question">Father</p>
    <p class="answer">Peter Evans</p>
    <p class="question">Status</p>
    <p class="answer">Unknown</p>
    <div class='brLarge'></div>
    <p class="question">Ex-Lover</p>
    <p class="answer">Nico... (That moment when you realize you never gave someone a last name-)</p>
    <p class="question">Status</p>
    <p class="answer">Alive</p>
    <div class='brLarge'></div>
    <p class="question">Son</p>
    <p class="answer"><a href='Jay.html'>Jay Star</a></p>
    <p class="question">Status</p>
    <p class="answer">Alive</p>`;
    document.querySelector('#Perception').innerHTML = `
    <p class="question">How they feel about themselves</p>
    <p class="answer">Currently, not that good. He is simply waiting for death to come, knowing he has brought only pain and misery to the world. But, if someone can snap him out of his depressive state, he's actually quite confident in his own abilities. He knows he's smart and crafty, he has full faith in himself</p>
    <div class='brLarge'></div>
    <p class="question">How they would describe themselves</p>
    <p class="answer">Again, depends on timing. Currently: A wretched blight to the world. When he's not depressed: Playful, inventive, efficient</p>
    <div class='brLarge'></div>
    <p class="question">What they think is their best trait</p>
    <p class="answer">His creativity</p>
    <div class='brLarge'></div>
    <p class="question">What they think is their worst trait</p>
    <p class="answer">His forgetfulness? In a sense...</p>
    <div class='brLarge'></div>
    <p class="question">How they think other perceive them</p>
    <p class="answer">Again, timing. Currently, he believes everyone wants him dead. That everyone would be happy to be rid of him. If he's in a better state, he might still think that a little, but he also knows that others view him as a leader; someone who can make something out of nothing.</p>
    <div class='brLarge'></div>
    <p class="question">What they would like to change about themselves</p>
    <p class="answer">His past</p>`;
    //document.querySelector('#Personality').innerHTML = ``;
};