window.onload = () => {
    getVersionNumber();
    let headStyles = `
    <link rel="stylesheet" href="CSS/HeadersAndDefaults.css?v=${versionNumber}">
    <link rel="stylesheet" href="CSS/Character.css?v=${versionNumber}">
    <link rel="stylesheet" href="CSS/Audioplayer.css?v=${versionNumber}">
    <link rel="stylesheet" href="CSS/HrStyles.css?v=${versionNumber}">
    <link rel="stylesheet" href="CSS/Nav.css?v=${versionNumber}">
    `;
    document.querySelector('head').innerHTML += headStyles;
    let player = document.querySelector('#player');
    player.pause();
    CreateNavbar();
    document.querySelector('#BasicInfo').innerHTML= `
    <p class="question">Birth Name</p>
    <p class="answer">Rene Risette Tickle</p>
    <p class="question">Current Name</p>
    <p class="answer">Rene Risette Tickle</p>
    <div class='brLarge'></div>
    <p class="question">First Name</p>
    <p class="answer">Rene</p>
    <p class="question">Meaning</p>
    <p class="answer">Reborn of born again</p>
    <div class='brLarge'></div>
    <p class="question">Middle Name</p>
    <p class="answer">Risette</p>
    <p class="question">Meaning</p>
    <p class="answer">"Pleasant little laugh:</p>
    <div class='brLarge'></div>
    <p class="question">Last Name</p>
    <p class="answer">Tickle</p>
    <div class='brLarge'></div>
    <p class="question">Nicknames</p>
    <p class="answer">...</p>
    <p><i>Reason</i></p>
    <p><i>...</i></p>
    <div class='brLarge'></div>
    <p class="question">Biological Gender</p>
    <p class="answer">Male</p>
    <p class="question">Preferred Gender</p>
    <p class="answer">Male</p>
    <p class="question">Pronouns</p>
    <p class="answer">He / him / his</p>
    <div class='brLarge'></div>
    <p class="question">Sexual Orientation</p>
    <p class="answer">Pansexual</p>
    <p class="question">Romantic Orientation</p>
    <p class="answer">Panromantic</p>
    <p class="answer">Open to poly relationships</p>
    <div class='brLarge'></div>
    <p class="question">Age</p>
    <p class="answer">19</p>
    <p class="question">Birthday</p>
    <p class="answer">February 3rd</p>
    <p class="question">Zodiac Sign</p>
    <p class="answer">Aquarius</p>
    <div class='brLarge'></div>
    <p class="question">Occupation</p>
    <p class="answer">Student</p>
    <div class='brLarge'></div>
    <p class="question">Where they live</p>
    <p class="answer">Prismoria</p>
    <div class='brLarge'></div>
    <p class="question">Languages</p>
    <p class="answer">English</p>
    <p class="answer">French</p>
    <p class="answer">German</p>`;
    document.querySelector('#Health').innerHTML = `
    <p class="question">Physical Illnesses</p>
    <p class="answer">None</p>
    <p class="question">Mental Illnesses</p>
    <p class="answer">Used to have depression</p>
    <div class='brLarge'></div>
    <p class="question">Triggers</p>
    <p class="answer">...</p>
    <p class="question">Addictions</p>
    <p class="answer">None</p>
    <div class='brLarge'></div>
    <p class="question">Mutation / Power</p>
    <p class="answer">Chameleon Characteristics</p>
    <p class="question">How long have they had it</p>
    <p class="answer">For about a year</p>
    <p class="question">What is it</p>
    <p class="answer">He has a horn like a horned chameleon, has a tail that can change colors, and can turn into a chameleon</p>`;
    document.querySelector('#Appearance').innerHTML = `
    <p class="question">Height</p>
    <p class="answer">6'3"</p>
    <p class="answer">190.5 cm</p>
    <p class="question">Weight</p>
    <p class="answer">154 lbs.</p>
    <p class="answer">69.85 kg</p>
    <div class='brLarge'></div>
    <p class="question">Skin color</p>
    <p class="answer">Rose Beige</p>
    <div class='brLarge'></div>
    <p class="question">Hair color</p>
    <p class="answer">Natural: Dark brown</p>
    <p class="answer">Current: He likes to change his hair color since his tail changes color all the time. He can never match his tail for good, so he embraced the rainbow. He might do a pink-purple gradient, a cyan-green gradient, red-orange gradient, anything.</p>
    <p class="question">Hair style</p>
    <p class="answer">Messy and fluffy</p>
    <div class='brLarge'></div>
    <p class="question">Eye color(s)</p>
    <p class="answer">Burnished Amber</p>
    <p class="question">Tail</p>
    <p class="question">Type</p>
    <p class="answer">Chameleon tail</p>
    <div class='brLarge'></div>
    <p class="question">Horn</p>
    <p class="question">Type</p>
    <p class="answer">Chameleon horn</p>
    <div class='brLarge'></div>
    <p class="question">Piercings</p>
    <p class="answer">Pierced ears</p>
    <p class="question">Scars</p>
    <p class="answer">None</p>
    <p class="question">Tattoos</p>
    <p class="answer">None</p>
    <p class="question">Birthmark</p>
    <p class="answer">None</p>
    <p class="question">Freckles</p>
    <p class="answer">Only on his shoulders</p>
    <div class='brLarge'></div>
    <p class="question">Glasses / Contacts</p>
    <p class="answer">None</p>
    <div class='brLarge'></div>
    <p class="question">Accent / Voice</p>
    <p class="answer">...</p>`;
    document.querySelector('#RpInfo').innerHTML=`
    <p class="question">Availability</p>
    <p class="answer">Open</p>
    <div class='brLarge'></div>
    <p class="question">Genres</p>
    <p class="answer">Fantasy</p>
    <p class="answer">Angst</p>
    <p class="answer">Sci-Fi</p>
    <p class="answer">Romance</p>
    <p class="answer">Mystery?</p>
    <p class="answer">Adventure</p>`;
    document.querySelector('#Relations').innerHTML=`
    <p class="question">Biological Mother</p>
    <p class="answer">xxx</p>
    <p class="question">Status</p>
    <p class="answer">...</p>
    <p class="question">Extra</p>
    <p class="answer">She was born born in America, but her parents were from France. That's why Rene has a French first and last name, but his last name is not.</p>
    <div class='brLarge'></div>
    <p class="question">Biological Father</p>
    <p class="answer">xxx</p>
    <p class="question">Status</p>
    <p class="answer">...</p>
    <div class='brLarge'></div>
    <p class="question">Sister</p>
    <p class="answer">...</p>
    <p class="question">Status</p>
    <p class="answer">...</p>
    <div class='brLarge'></div>
    <p class="question">Brother</p>
    <p class="answer">...</p>
    <p class="question">Status</p>
    <p class="answer">...</p>
    <div class='brLarge'></div>
    <p class="question">Friends</p>
    <p class="answer">...</p>`;
    document.querySelector('#Perception').innerHTML = `
    <p class='question'>How they feel about themselves</p>
    <p class='answer'>...</p>
    <div class='brLarge'></div>
    <p class='question'>How they would describe themselves</p>
    <p class='answer'>...</p>
    <div class='brLarge'></div>
    <p class='question'>What they think is their best trait</p>
    <p class='answer'>...</p>
    <div class='brLarge'></div>
    <p class='question'>What they think is their worst trait</p>
    <p class='answer'>...</p>
    <div class='brLarge'></div>
    <p class='question'>How they think other perceive them</p>
    <p class='answer'>...</p>
    <div class='brLarge'></div>
    <p class='question'>What they would like to change about themselves</p>
    <p class='answer'>...</p>`;
    document.querySelector('#Personality').innerHTML = `
    <p class="question">Closest Stereotype</p>
    <p class="answer">...</p>
    <p class="question">Overall Description</p>
    <p class="answer">Rene is a very playful and lighthearted guy. He loves messing around with those he's close to and will always be there for them. If a loved one asks for support on something, he will step in without question. And once they're feeling more comfortable and safe, then he'll start trying to cheer them back up, so they don't end the day on a bad note.</p>
    <p class="answer">He's also surprisingly smart and quick witted. He wants to be a game developer when he grows up and knows how to write some pretty robust and stable code. So he's really good with math, puzzles, and problem solving.</p>
    <div class='brLarge'></div>
    <p class="question">Likes</p>
    <p class="answer">Computer science and coding</p>
    <p class="answer">Teasing and joking around with friends, he loves to fluster people</p>
    <p class="answer"></p>
    <div class='brLarge'></div>
    <p class="question">Dislikes</p>
    <p class="answer">...</p>
    <p class="answer"></p>
    <p class="answer"></p>
    <div class='brLarge'></div>
    <p class="question">Positive Traits</p>
    <p class="answer">Playful and funny</p>
    <p class="answer">Understanding and supportive</p>
    <p class="answer"></p>
    <p class="answer"></p>
    <p class="question">Negative Traits</p>
    <p class="answer">...</p>
    <p class="answer"></p>
    <p class="answer"></p>
    <p class="answer"></p>
    <div class='brLarge'></div>
    <p class="question">Hobbies</p>
    <p class="answer">Coding</p>
    <p class="answer">Dying his hair</p>
    <div class='brLarge'></div>
    <p class="question">Greatest joy in life</p>
    <p class="answer">...</p>
    <div class='brLarge'></div>
    <p class="question">Fears</p>
    <p class="answer">...</p>
    <p class="answer"></p>
    <p class="answer"></p>
    <p class="answer"></p>
    <div class='brLarge'></div>
    <p class="question">Biggest Regret</p>
    <p class="answer">...</p>
    <div class='brLarge'></div>
    <p class="question">Biggest Accomplishment</p>
    <p class="answer">...</p>
    <div class='brLarge'></div>
    <p class="question">Darkest Secret</p>
    <p class="answer">...</p>`;
};